### ISSUE TITLE
DashboardClient should expose SendEvent method

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/plugin-library-for-octant#2]
`SendEvent` is [implemented on the client](https://github.com/vmware-tanzu/octant/blob/447171cf3ac3c520c3ad3bbe839f8affc6b61cc3/pkg/plugin/javascript/dashboard_send_event.go), but not exposed on the TypeScript interface.

```ts
  SendEvent(clientID: string, eventType: string, payload: any): string;
```

**Comment by wwitzel3** [comment]
Fixed here https://github.com/vmware-tanzu/plugin-library-for-octant/commit/840cdc3fedfcc2a8a698f31e4c80a970362ac359
