### ISSUE TITLE
Tag commits for npm releases

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/plugin-library-for-octant#6]
There are releases on npm, but no corresponding tags in this repo. Even better would be to publish to npm from a GitHub action triggered by a tag.

**Comment by scothis** [comment]
Created this issue before reading https://github.blog/changelog/2020-10-02-npm-automation-tokens 😂

**Comment by wwitzel3** [comment]
We now have an action that will publish both the yeoman-generator and the plugin library.
